[tool.hdev]
project_name = "checkmatelib"
project_type = "library"

[tool.hdev.tox]
# Any pip dependencies to be run before every test run (is prepended with
# "pip install") or false if no extras are required.
# e.g. flask=1.2.3 --no-deps
test_extras = false

[tool.hdev.run]
# Add custom commands accessible with `hdev run ...`

update-data.command="./bin/run/update_data.sh"
update-data.help="Download required data files for domain information"